"""Build a self-contained static demo of the app into dist-demo/.

The output runs entirely in the browser (no backend) using
demo/demo-mode.js as an in-memory API mock. This is what the hosted
Render demo serves: a static site never sleeps, so it always loads
instantly (unlike the previous Python web service on the free tier).

    uv run python build_demo.py
    python -m http.server -d dist-demo 8080   # preview locally

Usage:
    uv run python build_demo.py [--out dist-demo]
"""

import argparse
import base64
import json
import os
import re
import shutil
import tempfile
import uuid
from datetime import datetime, timedelta

# The data-dir env var must be set before importing app.models, which reads
# it at import time — hence the deliberate late imports below.
os.environ.setdefault("MISTRACKER_DATA_DIR", tempfile.mkdtemp(prefix="mistraker-build-"))

from flask import render_template

from app import create_app
from app.models import DEMO_MISTAKES, MISTAKE_TYPES, _parse_subtopics, _placeholder_png

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))


def build_demo_data() -> str:
    """Generate demo-data.js from the same source of truth as seed_demo()."""
    question_png = base64.b64encode(_placeholder_png(320, 180, (59, 130, 246))).decode()
    solution_png = base64.b64encode(_placeholder_png(320, 180, (16, 185, 129))).decode()
    base_time = datetime.now().astimezone()

    mistakes = []
    for i, entry in enumerate(DEMO_MISTAKES):
        subtopics = _parse_subtopics(entry["subtopics"])
        added_at = (base_time - timedelta(days=len(DEMO_MISTAKES) - i)).isoformat()
        mistakes.append(
            {
                "id": str(uuid.uuid4()),
                "category": entry["category"],
                "subtopics": subtopics,
                "subtopic": ", ".join(subtopics),
                "concept": entry["concept"],
                "topic": entry["category"],
                "question_image": f"data:image/png;base64,{question_png}",
                "solution_image": f"data:image/png;base64,{solution_png}",
                "mistake_type": entry["mistake_type"],
                "why_happened": entry["why_happened"],
                "how_to_avoid": entry["how_to_avoid"],
                "date_added": added_at,
                "date_modified": added_at,
                "archived": 0,
            }
        )

    payload = {"mistakeTypes": MISTAKE_TYPES, "mistakes": mistakes}
    return (
        "// Generated by build_demo.py — do not edit.\nwindow.DEMO_DATA = "
        + json.dumps(payload)
        + ";\n"
    )


def build(out_dir: str) -> None:
    out_abs = os.path.join(REPO_ROOT, out_dir)

    app = create_app()
    with app.test_request_context():
        html = render_template("index.html", mistake_types=MISTAKE_TYPES)

    # Make asset URLs relative so the page works under any base path.
    html = re.sub(r'((?:src|href)=")/static/', r"\1static/", html)

    # Load the demo data + fetch interceptor before main.js.
    html = html.replace(
        '<script src="static/js/main.js"></script>',
        "<script src=\"demo-data.js\"></script>\n"
        "    <script src=\"demo-mode.js\"></script>\n"
        '    <script src="static/js/main.js"></script>',
    )
    assert "demo-mode.js" in html, "main.js script tag not found in template"

    shutil.rmtree(out_abs, ignore_errors=True)
    shutil.copytree(os.path.join(REPO_ROOT, "static"), os.path.join(out_abs, "static"))

    # Expose favicon at the site root so /favicon.ico and /favicon.svg
    # resolve even when the browser ignores the <link rel="icon"> tag.
    # The SVG source is already in static/favicon.svg via copytree.
    _favicon_src = os.path.join(out_abs, "static", "favicon.svg")
    if os.path.exists(_favicon_src):
        shutil.copy(_favicon_src, os.path.join(out_abs, "favicon.svg"))
        shutil.copy(_favicon_src, os.path.join(out_abs, "favicon.ico"))

    with open(os.path.join(out_abs, "index.html"), "w") as f:
        f.write(html)
    shutil.copy(
        os.path.join(REPO_ROOT, "demo", "demo-mode.js"),
        os.path.join(out_abs, "demo-mode.js"),
    )
    with open(os.path.join(out_abs, "demo-data.js"), "w") as f:
        f.write(build_demo_data())

    size_kb = sum(
        os.path.getsize(os.path.join(root, name))
        for root, _, names in os.walk(out_abs)
        for name in names
    ) // 1024
    print(f"Built {out_dir}/ ({size_kb} KB)")
    print(f"Preview:  python -m http.server -d {out_dir} 8080")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="dist-demo")
    args = parser.parse_args()
    build(args.out)
